In [1]:
import numpy as np

def file_handling():
    lines = []

    with open('company.txt','r') as file:
        for line in file:
            values = line.strip().split(',')
            int_values = [int(val)for val in values]
            lines.append(int_values)

        data_frame = np.array([np.array(row) for row in lines], dtype = object)

        for row in data_frame:
            for i in row:
                print(type(i))

        return data_frame
def main():
    data_frame = file_handling()

    print(data_frame)

main()



[[10 20 30 40 50 60 70 80 90 100]
 [1 3 6 10 15 21 28 36 45 55]
 [1 4 9 16 25 36 49 64 81 100]]
